leftnav:
- identifier: ede0552d-22f5-7417-0493-34bb572c4ae0
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 05021787-eb15-1543-e078-f17230150229
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: cd5f26b3-031d-8e20-13d5-33c4d9ad97d6
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: aae62227-5d8d-38ef-6856-1a930308f80d
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: eea05059-aa9a-f888-dd65-49fcaa5b5949
  name: Exams
  pageRef: /pages/exams
  weight: 50
- identifier: 29a6acea-2c9a-4c96-62db-d87d049b0d3c
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 60
